apiVersion: v1
kind: Service
metadata:
  name: {{ include "discord.backend.fullname" . }}
  labels:
    {{- include "discord.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "discord.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
