{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord.backend.fullname" . }}
  labels:
    {{- include "discord.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.jwtSecret | quote }}
{{- end }}
